### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by GirishPatel** [landreussi/atom-todoist#1]
Installation is fine. After adding token, when we do **atom-todoiest -> toggle**, nothing happens.

**Comment by landreussi** [comment]
Hello @GirishPatel 

Which OS are you using? i've tested this package in windows, and doesn't work, in linux works like a charm. Maybe that's an incompatibility with the request package in windows.

It will be solved soon, I promise

**Comment by bvhme** [comment]
I have this issue on mac as well... :(

**Comment by landreussi** [comment]
Hello guys,

The package was updated and the bug was fixed.

The bug was due to splitting slashes of the path of the active projects, now the package splits '/' and '\\'

A screenshot of the package working like a charm (in windows):

https://user-images.githubusercontent.com/5938518/30070545-21d22a4a-923a-11e7-8689-16872230c8db.png
